name = "Brikhead"
uuid = "4a100c4f-64d8-47b9-a3b1-a577792216b4"
authors = ["Zaki A <zaki@live.ca> and contributors"]
version = "0.0.1"

[deps]
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
